version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run open:cover

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
